"""Initial structure creation

Revision ID: 8c05f196d162
Revises: 
Create Date: 2025-12-12 17:46:26.239163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c05f196d162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('debit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_conciliated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('negocio_conciliado', sa.String(length=255), nullable=True),
    sa.Column('num_factura_conciliado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio', sa.String(length=150), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=120), nullable=False),
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('telefono_secundario_1', sa.String(length=30), nullable=True),
    sa.Column('telefono_secundario_2', sa.String(length=30), nullable=True),
    sa.Column('telefono_secundario_3', sa.String(length=30), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('status_cliente', sa.String(length=20), nullable=True),
    sa.Column('requiere_factura', sa.Boolean(), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('regimen_fiscal', sa.String(length=4), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=4), nullable=True),
    sa.Column('mail_facturas', sa.String(length=120), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('otro_metodo_pago', sa.String(length=100), nullable=True),
    sa.Column('factura_pago', sa.Boolean(), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('motivo_descuento', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquete_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('paquete', sa.String(length=50), nullable=False),
    sa.Column('vigencia', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_vigencia', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('numero_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_enviado', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('otro_metodo_pago', sa.String(length=100), nullable=True),
    sa.Column('factura_pago', sa.Boolean(), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('paquete', sa.String(length=100), nullable=True),
    sa.Column('vigencia', sa.String(length=20), nullable=True),
    sa.Column('motivo_descuento', sa.String(length=150), nullable=True),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paquete_precio_id', sa.Integer(), nullable=True),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transaction.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['paquete_precio_id'], ['paquete_precio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_transaction_id')
    )
    op.create_table('suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('id_gumi', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('paquete', sa.String(length=100), nullable=False),
    sa.Column('vigencia', sa.String(length=20), nullable=False),
    sa.Column('vence_en', sa.Date(), nullable=True),
    sa.Column('proximo_pago', sa.Date(), nullable=True),
    sa.Column('es_sucursal', sa.Boolean(), nullable=True),
    sa.Column('matriz_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['matriz_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suscripcion')
    op.drop_table('pago')
    op.drop_table('user')
    op.drop_table('paquete_precio')
    op.drop_table('cliente')
    op.drop_table('bank_transaction')
    # ### end Alembic commands ###
